debug: true
server:
  port: 2020
  servlet:
    context-path: /spring-ai-project

logging:
  level:
    root: DEBUG

spring:
  http:
    client:
      factory: simple
  main:
    allow-bean-definition-overriding: true
  ai:
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 3030
        collection-name: my_collection
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: phi3:latest

# spring.ai.ollama.init.pull-model-strategy=when_missing # This will pull the model only if it's not already present