server:
  port: 2020
  servlet:
    context-path: /spring-ai-project

logging:
  level:
    root: DEBUG

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: phi3:latest

debug: true
